### ISSUE TITLE
Nutzerzahlenanzeige

### ISSUE THREAD

**Issue by mozita** [waldbrand/website#10]

**Comment by sebkur** [comment]
was ist hiermit gemeint?

**Comment by mozita** [comment]
Oh sorry, ich meine Besucherzahlenanzeige. Wie viele Nutzer den Editor schon genutzt haben. So ähnlich wie ein Button wie Seitenaufrufen auf Webseiten.

**Comment by sebkur** [comment]
achso, jut

**Comment by sebkur** [comment]
Juppie, wir haben jetzt Statistiken zum Editor. Auf der [Detailseite zum Editor](https://waldbrand-app.de/wes/editor) ganz unten in der aktuell letzten Kachel
