### ISSUE TITLE
Theme-Auswahlfenster im Editor entfernen

### ISSUE THREAD

**Issue by mozita** [waldbrand/website#27]
Die aufgeklappte Theme-Auswahl verwirrt die Leute, das Fenster entweder ganz löschen oder in minimierter Variante als Standard machen.

**Comment by sebkur** [comment]
ich hab das jetzt erstmal so eingestellt, dass es standardmäßig eingeklappt ist.

Wir können es natürlich auch komplett entfernen. Oder mit eigenem Inhalt füllen.
